import type { FishabilityRow } from "./types";

export const MOCK_RIVERS: FishabilityRow[] = [
  {
    river_id: "1",
    river_name: "Madison River",
    gauge_label: "West Yellowstone",
    usgs_site_no: "06037500",
    date: "2026-02-15",
    flow_cfs: 1210,
    median_flow_cfs: 450,
    flow_ratio_calc: 2.69,
    change_48h_pct_calc: -3.2,
    water_temp_f: 38.2,
    wind_am_mph: 4,
    wind_pm_mph: 12,
    fishability_score_calc: 92,
    bite_tier: "HOT",
  },
  {
    river_id: "2",
    river_name: "Yellowstone River",
    gauge_label: "Livingston",
    usgs_site_no: "06192500",
    date: "2026-02-15",
    flow_cfs: 2450,
    median_flow_cfs: 1800,
    flow_ratio_calc: 1.36,
    change_48h_pct_calc: 1.8,
    water_temp_f: 36.5,
    wind_am_mph: 2,
    wind_pm_mph: 8,
    fishability_score_calc: 85,
    bite_tier: "GOOD",
  },
  {
    river_id: "3",
    river_name: "Big Hole River",
    gauge_label: "Melrose",
    usgs_site_no: "06025500",
    date: "2026-02-15",
    flow_cfs: 380,
    median_flow_cfs: 320,
    flow_ratio_calc: 1.19,
    change_48h_pct_calc: -0.5,
    water_temp_f: null,
    wind_am_mph: 5,
    wind_pm_mph: 10,
    fishability_score_calc: 72,
    bite_tier: "FAIR",
  },
  {
    river_id: "4",
    river_name: "Bitterroot River",
    gauge_label: "Missoula",
    usgs_site_no: "12352500",
    date: "2026-02-15",
    flow_cfs: 890,
    median_flow_cfs: 1100,
    flow_ratio_calc: 0.81,
    change_48h_pct_calc: -2.1,
    water_temp_f: 35.1,
    wind_am_mph: 6,
    wind_pm_mph: 14,
    fishability_score_calc: 58,
    bite_tier: "TOUGH",
  },
  {
    river_id: "5",
    river_name: "Clark Fork",
    gauge_label: "St. Regis",
    usgs_site_no: "12354500",
    date: "2026-02-15",
    flow_cfs: 4200,
    median_flow_cfs: 3800,
    flow_ratio_calc: 1.11,
    change_48h_pct_calc: 0.3,
    water_temp_f: 37.0,
    wind_am_mph: 3,
    wind_pm_mph: 9,
    fishability_score_calc: 78,
    bite_tier: "GOOD",
  },
];
