-- Rivers metadata (for map markers + join to scores)
-- Columns: river, lat, lng (user schema) + latitude, longitude (scripts compatibility)
create table if not exists public.rivers (
  id bigint generated by default as identity primary key,
  river text not null unique,
  usgs_site_no text null,
  lat double precision,
  lng double precision,
  latitude double precision,
  longitude double precision,
  slug text unique,
  is_active boolean not null default true
);

-- Latest score per river (populated by ingest + run_daily_scoring)
create table if not exists public.river_daily_scores (
  id bigint generated by default as identity primary key,
  river text not null,
  date date not null,
  usgs_site_no text,
  fishability_score numeric,
  flow_cfs numeric,
  change_48h_pct numeric,
  water_temp_f numeric,
  wind_am_mph numeric,
  wind_pm_mph numeric,
  bite_tier text,
  median_flow_cfs numeric,
  flow_ratio_calc numeric,
  fishability_score_calc numeric,
  river_id text,
  river_name text,
  gauge_label text,
  created_at timestamptz not null default now(),
  unique (river, date)
);

create index if not exists idx_river_daily_scores_date on public.river_daily_scores (date desc);
create index if not exists idx_river_daily_scores_river on public.river_daily_scores (river);
create index if not exists idx_rivers_usgs on public.rivers (usgs_site_no);
