create table if not exists public.river_daily_observations (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  river text not null,
  date date not null,
  usgs_site_no text not null,
  flow_cfs numeric,
  water_temp_f numeric,
  source text not null default 'usgs_iv',
  unique (river, date, usgs_site_no)
);
